### ISSUE TITLE
This sample doesn't use the MAPI stub library

### ISSUE THREAD

**Issue by drvespa** [andreighita/mapi-smime-toolkit#1]
This sample should use the MAPI stub library since that's the recommended approach for Extended MAPI applications that are targeting Outlook 2010 and higher.

**Comment by stephenegriffin** [comment]
I can tackle this

**Comment by stephenegriffin** [comment]
I sent the pull request to your fork - you can pull to Andrei when you're ready:
https://github.com/drvespa/mapi-smime-toolkit/pull/2
