### ISSUE TITLE
Make the checkbox "Send these certificates with signed messages" also settable

### ISSUE THREAD

**Issue by RufusJWB** [andreighita/mapi-smime-toolkit#7]
Could you please make the checkbox "Send these certificates with signed messages" also settable?
![image](https://user-images.githubusercontent.com/1633499/153566036-ab2bf29c-41df-47fd-aab7-61954816a016.png)

According some analysis there should be a flag with the value 0x4:
![image](https://user-images.githubusercontent.com/1633499/153566101-42638494-922f-4692-89b7-f5dd7c91dbc6.png)

**Comment by drvespa** [comment]
This should now be addressed.
